"""add_energy_field_to_user

Revision ID: 63bbb028314d
Revises: bbb32a858580
Create Date: 2026-01-26 15:40:23.265236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63bbb028314d'
down_revision = 'bbb32a858580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=False)
    
    # 添加能量字段到user表
    op.add_column('user', sa.Column('energy', sa.Numeric(precision=10, scale=4), nullable=True, server_default='0.0000'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)
    
    # 删除能量字段
    op.drop_column('user', 'energy')

    # ### end Alembic commands ###
