"""add is_read field to notices table

Revision ID: 86f5762f2175
Revises: c4a1aabbb82b
Create Date: 2026-01-27 11:22:43.641896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86f5762f2175'
down_revision = 'c4a1aabbb82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=False)

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False))

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='提现地址',
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='提现金额',
               existing_nullable=False)
        batch_op.alter_column('withdrawal_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='提现方式: usdt, bank',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='状态: pending, processing, completed, failed',
               existing_nullable=False)
        batch_op.alter_column('order_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='提现订单号',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='备注信息',
               existing_nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='银行卡号',
               existing_nullable=True)
        batch_op.alter_column('bank_holder',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='账户名',
               existing_nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='银行名称',
               existing_nullable=True)
        batch_op.alter_column('bank_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='银行代码',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.alter_column('bank_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='银行代码',
               existing_nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='银行名称',
               existing_nullable=True)
        batch_op.alter_column('bank_holder',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='账户名',
               existing_nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='银行卡号',
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='备注信息',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('order_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='提现订单号',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='状态: pending, processing, completed, failed',
               existing_nullable=False)
        batch_op.alter_column('withdrawal_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='提现方式: usdt, bank',
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               comment='提现金额',
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='提现地址',
               existing_nullable=False)

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
