"""initial migration

Revision ID: 882b5343703d
Revises: 
Create Date: 2026-01-28 11:56:57.176292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882b5343703d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_rule',
    sa.Column('id', sa.Integer(), nullable=False, comment='规则ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='矿场代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='矿场名称'),
    sa.Column('miners_consumed', sa.Integer(), nullable=False, comment='消耗矿工数'),
    sa.Column('cycle_days', sa.Integer(), nullable=False, comment='周期天数'),
    sa.Column('energy_reward', sa.Numeric(precision=10, scale=4), nullable=False, comment='能量奖励'),
    sa.Column('background_image', sa.String(length=255), nullable=True, comment='背景图片'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='挖矿规则表'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='角色表'
    )
    op.create_table('support_email',
    sa.Column('id', sa.Integer(), nullable=False, comment='邮箱ID'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='邮箱地址'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='联系人姓名'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='支持邮箱表'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=80), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='密码哈希'),
    sa.Column('paypwd_hash', sa.String(length=128), nullable=True, comment='支付密码哈希'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='真实姓名'),
    sa.Column('id_number', sa.String(length=20), nullable=True, comment='身份证号'),
    sa.Column('id_front_image', sa.String(length=255), nullable=True, comment='身份证正面图片'),
    sa.Column('id_back_image', sa.String(length=255), nullable=True, comment='身份证背面图片'),
    sa.Column('invite_code', sa.String(length=8), nullable=False, comment='邀请码'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('balance', sa.Numeric(precision=20, scale=4), nullable=True, comment='余额'),
    sa.Column('energy', sa.Numeric(precision=10, scale=4), nullable=True, comment='能量值'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('invite_code'),
    sa.UniqueConstraint('username'),
    comment='用户表'
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False, comment='配置ID'),
    sa.Column('key', sa.String(length=255), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='关联用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    comment='配置表'
    )
    op.create_table('credit_card_generation_record',
    sa.Column('id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('generated_at', sa.DateTime(), nullable=True, comment='生成时间'),
    sa.Column('generated_by', sa.Integer(), nullable=False, comment='生成者ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['generated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='信用卡生成记录表'
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False, comment='文件ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_data', sa.LargeBinary(length=16777215), nullable=False, comment='文件数据'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文件表'
    )
    op.create_table('invite_relation',
    sa.Column('id', sa.Integer(), nullable=False, comment='关系ID'),
    sa.Column('inviter_id', sa.Integer(), nullable=False, comment='邀请人ID'),
    sa.Column('invitee_id', sa.Integer(), nullable=False, comment='被邀请人ID'),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='邀请关系表'
    )
    op.create_table('mine_user_relation',
    sa.Column('id', sa.Integer(), nullable=False, comment='关联ID'),
    sa.Column('mine_id', sa.Integer(), nullable=False, comment='矿场ID'),
    sa.Column('mine_code', sa.String(length=50), nullable=False, comment='矿场代码'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.ForeignKeyConstraint(['mine_id'], ['mining_rule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='矿场用户关联表'
    )
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False, comment='公告ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建用户ID'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='公告表'
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False, comment='通知ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='通知内容'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='通知表'
    )
    op.create_table('user_role_relation',
    sa.Column('id', sa.Integer(), nullable=False, comment='关联ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户角色关联表'
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='提现ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('address', sa.String(length=100), nullable=False, comment='提现地址'),
    sa.Column('amount', sa.Float(), nullable=False, comment='提现金额'),
    sa.Column('withdrawal_method', sa.String(length=20), nullable=False, comment='提现方式'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='提现状态'),
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='订单号'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('bank_account', sa.String(length=50), nullable=True, comment='银行账号'),
    sa.Column('bank_holder', sa.String(length=100), nullable=True, comment='持卡人姓名'),
    sa.Column('bank_name', sa.String(length=100), nullable=True, comment='银行名称'),
    sa.Column('bank_code', sa.String(length=50), nullable=True, comment='银行代码'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='审核人ID'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number'),
    comment='提现表'
    )
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False, comment='信用卡ID'),
    sa.Column('cardholder_name', sa.String(length=100), nullable=False, comment='持卡人姓名'),
    sa.Column('expiry_date', sa.String(length=10), nullable=False, comment='有效期'),
    sa.Column('card_number', sa.String(length=255), nullable=False, comment='卡号'),
    sa.Column('security_code', sa.String(length=10), nullable=False, comment='安全码'),
    sa.Column('recharge_status', sa.Boolean(), nullable=True, comment='充值状态'),
    sa.Column('recharge_count', sa.Integer(), nullable=True, comment='充值次数'),
    sa.Column('generation_record_id', sa.Integer(), nullable=True, comment='生成记录ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['generation_record_id'], ['credit_card_generation_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='信用卡表'
    )
    op.create_table('recharge',
    sa.Column('id', sa.Integer(), nullable=False, comment='充值ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='充值金额'),
    sa.Column('method', sa.String(length=50), nullable=False, comment='充值方式'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='充值状态'),
    sa.Column('screenshot_file_id', sa.Integer(), nullable=True, comment='截图文件ID'),
    sa.Column('bank_card_id', sa.Integer(), nullable=True, comment='银行卡ID'),
    sa.Column('order_number', sa.String(length=100), nullable=False, comment='订单号'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='审核人ID'),
    sa.ForeignKeyConstraint(['bank_card_id'], ['credit_card.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['screenshot_file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number'),
    comment='充值表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recharge')
    op.drop_table('credit_card')
    op.drop_table('withdrawals')
    op.drop_table('user_role_relation')
    op.drop_table('notification')
    op.drop_table('notices')
    op.drop_table('mine_user_relation')
    op.drop_table('invite_relation')
    op.drop_table('file')
    op.drop_table('credit_card_generation_record')
    op.drop_table('config')
    op.drop_table('user')
    op.drop_table('support_email')
    op.drop_table('role')
    op.drop_table('mining_rule')
    # ### end Alembic commands ###
