"""Increase balance field precision from (10,4) to (20,4)

Revision ID: b7e79be02716
Revises: a1b2c3d4e5f6
Create Date: 2026-01-27 13:07:50.043779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7e79be02716'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               type_=sa.Numeric(precision=20, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=20, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
