"""add_bank_fields_to_withdrawal

Revision ID: c4a1aabbb82b
Revises: 63bbb028314d
Create Date: 2026-01-26 15:59:51.206355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4a1aabbb82b'
down_revision = '63bbb028314d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=False)

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', sa.String(length=50), nullable=True, comment='银行卡号'))
        batch_op.add_column(sa.Column('bank_holder', sa.String(length=100), nullable=True, comment='账户名'))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True, comment='银行名称'))
        batch_op.add_column(sa.Column('bank_code', sa.String(length=50), nullable=True, comment='银行代码'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_column('bank_code')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_holder')
        batch_op.drop_column('bank_account')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
